### ISSUE TITLE
Python program to find a row max 1s in an array with 0s and 1s

### ISSUE THREAD

**Issue by mishrasunny-coder** [darkprinx/100-plus-Python-programming-exercises-extended#11]
Hello,

I am looking for the most efficient way of writing a program of array with binary values (0s and 1s) to find a row with max number of 1s.
For example if row 3 has max 1s then output should print row = 3

**Comment by darkprinx** [comment]
can you please give a sample test case?

**Comment by mishrasunny-coder** [comment]
Sure:
arr = [[0,0,0,1],
         [1,1,1,1],
          [0,1,0,1]]

This is  a binary array and I need to print the row with max 1s. In this case it will be 2nd row with Maximum number of 1s.
How do I write a program for this in python?

**Comment by darkprinx** [comment]
you can just print max(arr)
