### ISSUE TITLE
question 18: i have spent several hours solving this particular question but i just can't seem to get the result i am looking for.

### ISSUE THREAD

**Issue by laidstall1** [darkprinx/100-plus-Python-programming-exercises-extended#21]

**Comment by laidstall1** [comment]
#here's my code. 
#my program is supposed to check validity of the following passwords and return the ones that pass the check.

password =  input('Password: ').split(',')
valid_pass = []
low,up,dig,alnum = 0,0,0,0

for pas in password:
    if len(pas) >= 6 and len(pas) <= 12:
        pass
    for char in pas:
        if char.isupper():
            up+=1
        elif char.islower():
            low+=1
        elif char.isdigit():
            dig+=1
        elif char in ('!','@','#','$','%','^','&','*','(',')','_','-','+','='):
            alnum+=1
if (low>=1 and up >=1 and dig>=1 and alnum>=1 and low+up+dig+alnum == len(pas)):
    valid_pass.append(pas)
print(valid_pass)

**Comment by laidstall1** [comment]
#here's my code. 
#my program is supposed to check validity of the following passwords and return the ones that pass the check.

password =  input('Password: ').split(',')
valid_pass = []
low,up,dig,alnum = 0,0,0,0

for pas in password:
    if len(pas) >= 6 and len(pas) <= 12:
        pass
    for char in pas:
        if char.isupper():
            up+=1
        elif char.islower():
            low+=1
        elif char.isdigit():
            dig+=1
        elif char in ('!','@','#','$','%','^','&','*','(',')','_','-','+','='):
            alnum+=1
if (low>=1 and up >=1 and dig>=1 and alnum>=1 and low+up+dig+alnum == len(pas)):
    valid_pass.append(pas)
print(valid_pass)

**Comment by darkprinx** [comment]
the problem is in the condition,

if (low>=1 and up >=1 and dig>=1 and alnum>=1 and **low+up+dig+alnum == len(pas)**)

the bullet marked condition doesn't go with the question's requirement.

**Comment by laidstall1** [comment]
okay, thanks a bunch mate. 
could you please make it clearer on how to fix this?

**Comment by darkprinx** [comment]
just remove the part of the condition I mentioned. I hope it will work.
